// frontend/apps/nuxt/components/image-card/image-card.vue
<script setup lang="ts">
import { RouterLinkProps } from 'vue-router';
import { IProgressiveImageProps } from '../progressive-image/progressive-image-props';

interface IProps {
  linkProps: RouterLinkProps;
  title: string;
  imageUrls?: Omit<IProgressiveImageProps, 'alt'>;
}

const { imageUrls, linkProps, title } = defineProps<IProps>();
const alt = `Cover image of the item ${title}`;
</script>
<style lang="css" scoped>
.card:hover {
  transform: rotateX(25deg);
  box-shadow: 0px 10px 10px -5px var(--color-fuchsia-300);
}
</style>
<template>
  <!-- TODO DOES NOT WORK WITH FILETREE AND FILENODE TOGETHER => FIX -->
  <article class="card card-border bg-slate-800">
    <div class="relative h-56" :class="{ 'bg-fuchsia-800': !imageUrls }">
      <ProgressiveImage
        v-if="imageUrls"
        :alt="alt"
        :highQualityImageUrl="
          imageHandler.getImageUrlForId(imageUrls?.highQualityImageUrl)
        "
        :lowQualityImageUrl="
          imageHandler.getImageUrlForId(imageUrls?.lowQualityImageUrl)
        "
      />
    </div>
    <div class="card-body h-28">
      <!-- TODO hover styles -->
      <NuxtLink class="hover:text-fuchsia-400" :to="linkProps.to">
        <h2
          class="line-clamp-3 overflow-hidden font-bold text-ellipsis"
          card-title
        >
          {{ title }}
        </h2>
      </NuxtLink>
    </div>
  </article>
</template>

// frontend/src/sharedComponents/card/ImageCard.tsx
import { Link as TanStackRouterLink } from '@tanstack/react-router';
import { ProgressiveImage } from '../progressiveImage/ProgressiveImage';
import styles from './ImageCard.module.css';
import type { IProgressiveImageProps } from '../progressiveImage/ProgressiveImage';
import type { LinkOptions } from '@tanstack/react-router';
import type { JSX } from 'react';
import { baseLinkStyles } from '$lib/styles/baseLinkStyles';

interface ICardProps {
  title: string;
  children?: JSX.Element;
  imageUrls?: Omit<IProgressiveImageProps, 'alt'>;
  linkOptions: LinkOptions;
}

export function ImageCard({ title, imageUrls, linkOptions }: ICardProps) {
  return (
    <>
      <article className={`card image-full ${styles.card}`}>
        {imageUrls && (
          <ProgressiveImage
            {...imageUrls}
            alt={`Cover image of the item ${title}`}
          />
        )}
        <div
          role="presentation"
          className={`card-body ${styles['card-body']} bg-linear-to-t from-slate-800 from-[5ch] to-[20ch] p-2`}
        >
          <header className="card-title">
            <h1
              title={title}
              className="max-w-text line-clamp-3 overflow-hidden font-bold text-ellipsis whitespace-normal"
            >
              <TanStackRouterLink
                {...linkOptions}
                className={`${baseLinkStyles} block h-full w-full`}
              >
                {title}
              </TanStackRouterLink>
            </h1>
          </header>
        </div>
      </article>
    </>
  );
}
