// frontend/apps/react/src/features/playerCompound/PlayerCompound.tsx
import type { IFileNode } from '@videos-with-subtitle-player/core';
import { Player } from './player/Player';
import { Playlist } from './playlist/Playlist';

interface IPlayerCompoundProps {
  currentFile: IFileNode;
  siblings: IFileNode[];
}

export function PlayerCompound({
  currentFile,
  siblings,
}: IPlayerCompoundProps) {
  return (
    <div className="flex gap-4">
      <Player
        key={currentFile.id}
        audioId={currentFile.id}
        subtitleId={currentFile.subtitleFileId}
        fileType={currentFile.fileType}
      />

      <Playlist siblings={siblings} />
    </div>
  );
}

// frontend/apps/nuxt/app/components/player-compound/player-compound.vue
<script setup lang="ts">
import { IFileNode } from '@videos-with-subtitle-player/core';

interface IProps {
  currentFile: IFileNode;
  siblings: IFileNode[];
  folderId: string;
}

const { siblings, currentFile, folderId } = defineProps<IProps>();
</script>
<template>
  <div className="flex gap-4">
    <player
      :audioId="currentFile.id"
      :fileType="currentFile.fileType"
      :subtitleId="currentFile.subtitleFileId"
    />
    <playlist :items="siblings" :folderId="folderId" :fileId="currentFile.id" />
  </div>
</template>
