// frontend/apps/nuxt/components/image-card/image-card.vue
<script setup lang="ts">
import { RouterLinkProps } from 'vue-router';

interface IProps {
  linkProps: RouterLinkProps;
  title: string;
  imageUrl?: string;
}

const { imageUrl, linkProps, title } = defineProps<IProps>();
</script>
<style lang="css" scoped>
.card:hover {
  transform: rotateX(25deg);
  box-shadow: 0px 10px 10px -5px var(--color-fuchsia-300);
}
</style>
<template>
  <!-- TODO DOES NOT WORK WITH FILETREE AND FILENODE TOGETHER => FIX -->
  <article class="card card-border bg-slate-800">
    <figure class="h-56" :class="{ 'bg-fuchsia-800': !imageUrl }">
      <img
        v-if="imageUrl"
        loading="lazy"
        :src="imageHandler.getImageUrlForId(imageUrl)"
        :alt="`Cover image of the item ${title}`"
      />
    </figure>
    <div class="card-body h-28">
      <!-- TODO hover styles -->
      <NuxtLink class="hover:text-fuchsia-400" :to="linkProps.to">
        <h2
          class="line-clamp-3 overflow-hidden font-bold text-ellipsis"
          card-title
        >
          {{ title }}
        </h2>
      </NuxtLink>
    </div>
  </article>
</template>

// frontend/apps/react/src/sharedComponents/card/ImageCard.tsx
import { baseLinkStyles } from '$lib/styles/baseLinkStyles';
import {
  Link as TanStackRouterLink,
  type LinkOptions,
} from '@tanstack/react-router';
import type { JSX } from 'react';
import styles from './ImageCard.module.css';
interface ICardProps {
  title: string;
  children?: JSX.Element;
  imageUrl?: string;
  linkOptions: LinkOptions;
}

export function ImageCard({ title, imageUrl, linkOptions }: ICardProps) {
  return (
    <article
      className={`${styles.card} ${imageUrl ? undefined : 'bg-fuchsia-800'}`}
    >
      {imageUrl && (
        <img
          loading="lazy"
          src={imageUrl}
          className={styles['card-image']}
          alt={`Cover image of the item ${title}`}
        />
      )}
      <div role="presentation">
        <div
          role="presentation"
          className="flex h-full items-end bg-linear-to-t from-slate-800 from-[5ch] to-[20ch]"
        >
          <header className="h-fit overflow-hidden rounded-b-md p-4">
            <h1
              className="max-w-text line-clamp-3 overflow-hidden font-bold text-ellipsis whitespace-normal"
              title={title}
            >
              <TanStackRouterLink
                {...linkOptions}
                className={`${baseLinkStyles} block h-full w-full`}
              >
                {title}
              </TanStackRouterLink>
            </h1>
          </header>
        </div>
      </div>
    </article>
  );
}
