// frontend/src/sharedComponents/progressiveImage/ProgressiveImage.tsx
import { useState } from 'react';
import styles from './ProgressiveImage.module.css';

export interface IProgressiveImageProps {
  highQualityImageUrl: Maybe<string>;
  lowQualityImageUrl: Maybe<string>;
  alt: string;
}

export function ProgressiveImage({
  highQualityImageUrl,
  lowQualityImageUrl,
  alt,
}: IProgressiveImageProps) {
  // TODO INTERSECTION OBSERVER for performance => one observer for all
  const [isHighQualityImageLoaded, setIsHighQualityImageLoaded] =
    useState<boolean>(false);

  if (!highQualityImageUrl) {
    return null;
  }

  return (
    <figure className={styles['progressive-image-container']}>
      {lowQualityImageUrl && (
        <img
          loading="eager"
          src={lowQualityImageUrl}
          className={`${styles['progressive-image']} ${styles['low-quality']} ${isHighQualityImageLoaded ? styles['hidden'] : ''}`}
          alt={alt}
        />
      )}
      {highQualityImageUrl && (
        <img
          loading="lazy"
          src={highQualityImageUrl}
          className={`${styles['progressive-image']} ${styles['high-quality']} ${isHighQualityImageLoaded ? '' : styles['hidden']}`}
          alt={alt}
          onLoad={() => setIsHighQualityImageLoaded(true)}
        />
      )}
    </figure>
  );
}

// frontend/apps/nuxt/components/progressive-image/progressive-image.vue
<script setup lang="ts">
import { IProgressiveImageProps } from './progressive-image-props';

const { alt, highQualityImageUrl, lowQualityImageUrl } =
  defineProps<IProgressiveImageProps>();

const isHighQualityImageLoaded = ref<boolean>(false);
</script>
<style lang="css" scoped>
.progressive-image-container {
  position: relative;
  height: 100%;
  width: 100%;
  overflow: hidden;
}

.progressive-image {
  position: absolute;
  height: 100%;
  width: 100%;
  object-fit: contain;

  /* hide alt text */
  font-size: 0;

  transition:
    opacity 0.6s ease-in-out,
    visibility 0.6s ease-in-out;

  &.low-quality {
    filter: blur(10px);
  }

  &.high-quality {
    filter: none;
  }

  &.hiddenImage {
    visibility: hidden;
    opacity: 0;
  }
}
</style>
<template>
  <div class="progressive-image-container">
    <img
      v-if="lowQualityImageUrl"
      loading="eager"
      :src="lowQualityImageUrl"
      class="progressive-image low-quality"
      :class="{ hiddenImage: isHighQualityImageLoaded }"
      :alt="alt"
    />
    <ClientOnly>
      <img
        v-if="highQualityImageUrl"
        loading="lazy"
        :src="highQualityImageUrl"
        class="progressive-image high-quality"
        :class="{ hiddenImage: !isHighQualityImageLoaded }"
        :alt="alt"
        @load="isHighQualityImageLoaded = true"
      />
    </ClientOnly>
  </div>
</template>
