// frontend/apps/nuxt/components/playlist/playlist.vue
<script setup lang="ts">
import { IFileNode } from '@videos-with-subtitle-player/core';

interface IProps {
  items: IFileNode[];
  folderId: string;
  fileId: string;
}

const { items, fileId, folderId } = defineProps<IProps>();
const labelId = useId();

function getAriaLabel(fileName: string): string {
  return `Play '${fileName}''`;
}
</script>

<template>
  <section :aria-labelledby="labelId">
    <h2 :id="labelId" class="mb-2 text-base font-bold">Playlist</h2>
    <ol class="list h-96 w-80 overflow-y-scroll">
      <li v-for="item in items" class="list-row">
        <NuxtLink
          :title="item.name"
          :aria-label="getAriaLabel(item.name)"
          :to="{
            name: 'folders-folderId-files-fileId',
            params: { fileId: item.id, folderId },
          }"
          :aria-selected="item.id === fileId ? 'true' : 'false'"
          class="hover:text-fuchsia-400"
          :class="{
            'text-fuchsia-500': item.id === fileId,
          }"
        >
          {{ item.name }}
        </NuxtLink>
      </li>
    </ol>
  </section>
</template>

// frontend/src/features/playerCompound/playlist/Playlist.tsx
import { IFileNode } from '$models/fileTree';
import { useId } from 'react';
import { Route } from '../../../routes/folders/_folderLayout/$folderId/files/$fileId';
import { PlaylistItem } from './PlaylistItem';

interface IPlaylistProps {
  siblings: IFileNode[];
}

export function Playlist({ siblings }: IPlaylistProps) {
  const labelId = useId();
  const { folderId, fileId } = Route.useParams();

  return (
    <section aria-labelledby={labelId}>
      <h2 id={labelId} className="mb-2 text-base font-bold">
        Playlist
      </h2>
      <ul className="flex h-80 flex-col gap-1 overflow-y-auto overflow-x-hidden">
        {siblings.map((item) => (
          <PlaylistItem
            key={item.id}
            isActive={item.id === fileId}
            item={item}
            folderId={folderId}
          />
        ))}
      </ul>
    </section>
  );
}
