// frontend/apps/nuxt/components/error-message/error-message.vue
<script setup lang="ts">
interface IProps {
  message: string;
  description?: string;
}

const { message, description } = defineProps<IProps>();
</script>
<template>
  <section className="h-fit rounded-md bg-red-50 p-4 text-red-900">
    <h1 className="text-lg font-bold">{{ message }}</h1>
    <p v-if="description">{{ description }}</p>
  </section>
</template>

// frontend/src/sharedComponents/errorMessage/ErrorMessage.tsx
interface IErrorMessageProps {
  error: unknown;
  message: string;
  description?: string;
}

export function ErrorMessage({
  error,
  message,
  description,
}: IErrorMessageProps) {
  console.error(error);
  // TODO IMPROVE
  return (
    <section className="h-fit rounded-md bg-red-50 p-4 text-red-900">
      <h1 className="text-lg font-bold">{message}</h1>
      <p>{description}</p>
    </section>
  );
}
