// frontend/apps/react/src/sharedComponents/folderList/FolderList.tsx
import { imageHandler } from '$lib/styles/imageHandler';
import { ImageCard } from '$sharedComponents/card/ImageCard';
import type { LinkOptions } from '@tanstack/react-router';
import { type IFileTree } from '@videos-with-subtitle-player/core';

interface IFolderListSectionProps {
  folders: IFileTree[];
}

export function FolderList({ folders }: IFolderListSectionProps) {
  return (
    <ol className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
      {folders.map((child) => {
        const linkOption: LinkOptions = {
          to: '/folders/$folderId',
          params: { folderId: child.id },
        };
        return (
          <li key={child.id}>
            <ImageCard
              linkOptions={linkOption}
              title={child.name}
              imageUrls={{
                highQualityImageUrl: imageHandler.getImageUrlForId(
                  child.thumbnailId,
                ),
                lowQualityImageUrl: imageHandler.getImageUrlForId(
                  child.lowQualityThumbnailId,
                ),
              }}
            />
          </li>
        );
      })}
    </ol>
  );
}

// frontend/apps/nuxt/components/folder-list/folder-list.vue
<script setup lang="ts">
import { IFileTree } from '@videos-with-subtitle-player/core';

interface IProps {
  folders: IFileTree[];
}

const { folders } = defineProps<IProps>();
</script>

<template>
  <p v-if="!folders.length">no sub folders</p>
  <ul
    v-else
    className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"
  >
    <li v-for="folder in folders">
      <image-card
        :imageUrls="{
          highQualityImageUrl: folder.thumbnailId,
          lowQualityImageUrl: folder.lowQualityThumbnailId,
        }"
        :title="folder.name"
        :linkProps="{
          to: { name: 'folders-folderId', params: { folderId: folder.id } },
        }"
        :folder="folder"
        :key="folder.id"
      />
    </li>
  </ul>
</template>
