// frontend/src/sharedComponents/player/Player.tsx
import { FileType } from '$enums/FileType';

const baseUrl = import.meta.env.VITE_BASE_URL;

interface IPlayerProps {
  audioId: string;
  subtitleId?: string;
  fileType: FileType;
}

export function Player({ audioId, subtitleId, fileType }: IPlayerProps) {
  return (
    <div style={{ flexGrow: 1 }}>
      <video
        controls
        style={{ width: '100%' }}
        crossOrigin="anonymous"
        autoPlay
      >
        <source
          type="audio/mp3"
          src={`${baseUrl}/api/file/continuous/${audioId}`}
        />
        {fileType === FileType.AUDIO && subtitleId && (
          <track
            default
            kind="captions"
            srcLang="en"
            src={`${baseUrl}/api/file/discrete/${subtitleId}`}
          />
        )}
      </video>
    </div>
  );
}

// frontend/apps/nuxt/app/components/player/player.vue
<script setup lang="ts">
import { FileType } from '@videos-with-subtitle-player/core';

interface IProps {
  audioId: string;
  subtitleId?: string;
  fileType: FileType;
}

const { audioId, fileType, subtitleId } = defineProps<IProps>();

// TODO ENV VARIABLE
const baseUrl = 'http://localhost:3000';

const audioSource = `${baseUrl}/api/file/continuous/${audioId}`;
const subtitleSource = `${baseUrl}/api/file/discrete/${subtitleId}`;
</script>
<template>
  <div class="grow">
    <video
      controls
      class="w-full"
      crossOrigin="anonymous"
      autoPlay
      data-testid="video"
    >
      <source type="audio/mp3" :src="audioSource" data-testid="source" />
      <track
        v-if="fileType === FileType.AUDIO && subtitleId"
        default
        kind="captions"
        srcLang="en"
        :src="subtitleSource"
        data-testid="track"
      />
    </video>
  </div>
</template>
